name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:

    - uses: actions/checkout@v4
    - name: Setup
      uses: actions/setup-node@v4

    - name: Install
      run: npm install bslint

    - name: Lint
      run: npm run lint
